<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_karyawan extends CI_Model
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('m_nilai');
    }

    function searchForId($id, $keys, $array) {
       foreach ($array as $key => $val) {
           if ($val[$keys] === $id) {
               return $key;
           }
       }
       return null;
    }

    function proses_karyawan()
    {

        if ($this->input->post('tipe')=="save"){
            $tanggal = substr($this->input->post('tanggalLahir'),8,2);
            $bulan = substr($this->input->post('tanggalLahir'),5,2);
            $tahun = substr($this->input->post('tanggalLahir'),0,4);
            $tanggalLahir2 = $tanggal."/".$bulan."/".$tahun;

            $upper = strtoupper($this->input->post('nama'));
            $kata = explode(" ",$upper,2);
            $username = "";
            $password = "";
            foreach($kata as $k){
                $username .= substr($k,0,3);
                $password .= $k[0];
            }
            $usernames = $username.$tanggal.$bulan;
            $password.= "@".$tanggal.$bulan."!";
            $cekUsername = $this->db->get_where('list_karyawan',array('username'=>$usernames))->row_array();
            $cekEmail = $this->db->get_where('list_karyawan',array('email'=>$this->input->post('email')))->row_array();

            if ($cekUsername!==null){
                return array('hasil'=>'adaUsername');
            } else if ($cekEmail!==null){
                return array('hasil'=>'adaEmail');
            } else {

                $data = array(
                    'nik'            => $this->input->post('nik'),
                    'nama'           => ucwords($this->input->post('nama')),
                    'jenisKelamin'   => $this->input->post('jenisKelamin'),
                    'tanggalLahir'   => $this->input->post('tanggalLahir'),
                    'agama'          => $this->input->post('agama'),
                    'nomorHandphone' => $this->input->post('nomorHandphone'),
                    'email'          => $this->input->post('email'),
                    'alamat'         => $this->input->post('alamat'),
                    'username'       => $usernames,
                    'password'       => $password,
                    'role'           => $this->input->post('role')
                );
                $data2 = array(
                    'nama'      =>  ucwords($this->input->post('nama')),
                    'username'  =>  $usernames,
                    'password'  =>  $password,
                    'email'     =>  $this->input->post('email')
                );

                // $this->load->view('send/mail?'.'nama='.$data['nama'].'&username='.$usernames.'&password='.$password.'&email='.$data['email'],null,TRUE);
                $this->db->insert('list_nilai',array('nik'=>$this->input->post('nik')));
                $simpan = $this->db->insert('list_karyawan',$data);

                if ($simpan==true){
                    return $data2;
                } else {
                    return json_encode(false);
                }
            }

            // echo "save";

        } else if ($this->input->post('tipe')=="update"){

            $dataBaru = array(
              'nama'          => ucwords($this->input->post('nama')),
              'jenisKelamin'  => $this->input->post('jenisKelamin'),
              'tanggalLahir'  => $this->input->post('tanggalLahir'),
              'email'         => $this->input->post('email'),
              'agama'         => $this->input->post('agama'),
              'nomorHandphone'=> $this->input->post('nomorHandphone'),
              'alamat'        => $this->input->post('alamat'),
              'username'        => $this->input->post('username'),
              'password'        => $this->input->post('password'),
              'role'          => $this->input->post('role')
            );
            $cekEmail = $this->db->get_where('list_karyawan',array('email'=>$this->input->post('email')))->row_array();
            $cekUsername = $this->db->get_where('list_karyawan',array('username'=>$this->input->post('username')))->row_array();
            if ($cekEmail !== null and $cekEmail['nik']!==$this->input->post('nik')){
                return array('hasil'=>'adaEmail');
            } else if ($cekUsername !== null and $cekUsername['nik']!==$this->input->post('nik')){
                return array('hasil'=>'adaUsernames');
            }else {
                if ($this->input->post('role')==1){
                  $this->db->delete('list_nilai',array('nik'=>$this->input->post('nik')));
                }
                $this->db->where('nik',$this->input->post('nik'));
                $update = $this->db->update('list_karyawan',$dataBaru);
                if ($update==true){
                    // return array('hasil'=>'success');
                    return array('hasil'=>'success');
                } else {
                    return array('hasil'=>'failed');
                }
            }

            // echo "update";

        } else if ($this->input->post('tipe')=="delete"){
            $this->db->delete('list_nilai',array('nik'=>$this->input->post('nik')));

            // $this->m_nilai->hitung();

            return $this->db->delete('list_karyawan',array('nik'=>$this->input->post('nik')));

            // echo "delete";

        }
    }

    function get_karyawan($id)
    {
        return $this->db->get_where('list_karyawan',array('nik'=>$id))->row_array();
    }

    function get_username($id)
    {
        return $this->db->get_where('list_karyawan',array('username'=>$id))->row_array();
    }

    function get_nik_karyawan()
    {
        $this->db->select('nik')
                 ->from('list_karyawan');
        return $this->db->get()->row_array();
    }

    function karyawan_belum_dinilai()
    {
        $all_kriteria = $this->m_kriteria->get_all_kriteria();
        $num_kriteria = $this->m_kriteria->get_num_kriteria();
        $sql = "SELECT a.nik, a.nama FROM `list_karyawan` a LEFT JOIN `list_nilai` b on a.nik = b.nik where ";
        $i = 1;
        foreach ($all_kriteria as $ak) {
        	$sql .= "b.`{$ak['kode']}` = 0";
        	if ($i!=$num_kriteria){
        		$sql .= " or ";
        	}
        	$i++;
        }
        $sql .= " order by nik ASC";
        return $this->db->query($sql)->result_array();
    }

    function karyawan_belum_dinilais()
    {
      $all_kriteria = $this->m_kriteria->get_all_kriteria();
      $num_kriteria = $this->m_kriteria->get_num_kriteria();
      $sql = "SELECT a.nik, a.nama FROM `list_karyawan` a LEFT JOIN `list_nilai` b on a.nik = b.nik where ";
      $i = 1;
      foreach ($all_kriteria as $ak) {
        $sql .= "b.`{$ak['kode']}` = 0";
        if ($i!=$num_kriteria){
          $sql .= " or ";
        }
        $i++;
      }
      $sql .= " order by nama ASC";
      return $this->db->query($sql)->result_array();
    }

    function get_all_karyawan()
    {
        $this->db->order_by('nik', 'asc');
        return $this->db->get('list_karyawan')->result_array();
    }

    function get_all_karyawans()
    {
        $this->db->order_by('nama', 'asc');
        return $this->db->get('list_karyawan')->result_array();
    }

    function get_num_karyawan()
    {
        return $this->db->get('list_karyawan')->num_rows();
    }

}
