<?php
/*
 * Generated by CRUDigniter v3.2
 * www.crudigniter.com
 */

class M_login extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function login()
    {

    }

    function register()
    {

    }

    function forgot()
    {

    }


}
